# Generated by Django 5.2.7 on 2025-10-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='完整的域名 FQDN（如 example.com），统一小写存储', max_length=255, unique=True, verbose_name='域名')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
                'db_table': 'domains',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__exact', models.Func(models.F('name'), function='LOWER'))), name='domain_name_lowercase')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='组织名称')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('domains', models.ManyToManyField(related_name='organizations', to='assets.domain', verbose_name='关联域名')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'organizations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='完整的子域名 FQDN（如 api.example.com），统一小写存储', max_length=255, verbose_name='子域名')),
                ('is_root', models.BooleanField(db_index=True, default=False, help_text='Domain 自动创建的同名子域名，受保护不允许删除', verbose_name='是否为根子域名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='assets.domain', verbose_name='所属域名')),
            ],
            options={
                'verbose_name': '子域名',
                'verbose_name_plural': '子域名',
                'db_table': 'subdomains',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__exact', models.Func(models.F('name'), function='LOWER'))), name='subdomain_name_lowercase')],
                'unique_together': {('domain', 'name')},
            },
        ),
    ]
