# Generated by Django 5.2.7 on 2025-10-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='完整的域名 FQDN（如 example.com），统一小写存储', max_length=255, unique=True, verbose_name='资产名称')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述信息')),
                ('type', models.CharField(db_index=True, default='domain', help_text='资产类型：domain（域名）/ ip（IP地址）/ cidr（网段），默认为 domain', max_length=20, verbose_name='资产类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'assets',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__exact', models.Func(models.F('name'), function='LOWER'))), name='asset_name_lowercase')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='组织名称')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('assets', models.ManyToManyField(related_name='organizations', to='assets.asset', verbose_name='关联资产')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'organizations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='完整的域名 FQDN（如 api.example.com），统一小写存储', max_length=255, verbose_name='域名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='assets.asset', verbose_name='所属资产')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
                'db_table': 'domains',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name__exact', models.Func(models.F('name'), function='LOWER'))), name='domain_name_lowercase')],
                'unique_together': {('asset', 'name')},
            },
        ),
    ]
