# Generated by Django 5.2.7 on 2025-10-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('name',), name='domain_name_unique'),
        ),
    ]
