# Generated by Django 5.2.7 on 2025-10-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='endpoint',
            table='endpoints',
        ),
    ]
