"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方应用
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    # 业务应用
    'apps.common',   # 通用工具
    'apps.targets',  # 扫描目标管理
    'apps.scan',     # 扫描任务管理
    'apps.engine',   # 扫描引擎管理
    'apps.asset',    # 资产管理
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 中间件（必须在 CommonMiddleware 之前）
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # 已禁用 CSRF 校验
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 添加自定义模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database - PostgreSQL 配置
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'xingrin'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        
        # 连接池配置：保持连接 10 分钟
        'CONN_MAX_AGE': 600,
        
        # PostgreSQL 特定选项
        'OPTIONS': {
            'connect_timeout': 10,  # 连接超时 10 秒
            'options': '-c statement_timeout=30000'  # SQL 语句超时 30 秒
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'zh-hans')

TIME_ZONE = os.getenv('TIME_ZONE', 'Asia/Shanghai')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== REST Framework 配置 ====================
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.BasePagination',  # 使用基础分页器
    
    # 禁用 CSRF 检查（所有环境）
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    
    # JSON 命名格式转换：后端 snake_case ↔ 前端 camelCase
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',  # 响应数据转换为 camelCase
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',  # 浏览器 API 也使用 camelCase
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',  # 请求数据从 camelCase 转换为 snake_case
        'djangorestframework_camel_case.parser.CamelCaseFormParser',  # 表单数据也支持转换
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',  # 文件上传支持转换
    ),
    
    # 转换配置
    'JSON_UNDERSCOREIZE': {
        'no_underscore_before_number': True,  # 数字前不加下划线 (field1 不会变成 field_1)
    },
}

# ==================== CORS 配置 ====================
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

# ==================== CSRF 配置 ====================
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')

# ==================== Prefect 配置 ====================
# Prefect API 服务器地址
PREFECT_API_URL = os.getenv('PREFECT_API_URL', 'http://localhost:4200/api')

# Prefect 数据库配置（使用独立的 prefect 数据库）
# 注意：需要在 PostgreSQL 中创建 prefect 数据库
PREFECT_DATABASE_NAME = os.getenv('PREFECT_DATABASE_NAME', 'prefect')

# Prefect 工作池名称
PREFECT_DEFAULT_WORK_POOL_NAME = os.getenv('PREFECT_DEFAULT_WORK_POOL_NAME', 'default')

# Prefect task超时配置
PREFECT_TASK_DEFAULT_TIMEOUT_SECONDS = int(os.getenv('PREFECT_TASK_DEFAULT_TIMEOUT_SECONDS', '3600'))  # 默认超时：1小时

# subprocess 默认超时配置（用于扫描工具命令）
SUBPROCESS_DEFAULT_TIMEOUT_SECONDS = int(os.getenv('SUBPROCESS_DEFAULT_TIMEOUT_SECONDS', '3600'))  # 默认超时：1小时

# 任务重试配置
PREFECT_TASK_DEFAULT_RETRIES = int(os.getenv('PREFECT_TASK_DEFAULT_RETRIES', '3'))  # 默认重试次数
PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS = int(os.getenv('PREFECT_TASK_DEFAULT_RETRY_DELAY_SECONDS', '60'))  # 重试延迟：60秒

# Prefect 日志级别
PREFECT_LOGGING_LEVEL = os.getenv('PREFECT_LOGGING_LEVEL', 'INFO')


# ==================== 扫描结果存储和清理配置 ====================
# 扫描结果存储目录
# 
# 说明：
# - 所有扫描任务的工作空间都创建在此目录下
# - 清理任务会扫描此目录下的所有子目录
# - 必须配置，否则扫描任务无法创建工作空间
# 
# 配置方式：
# - 环境变量：SCAN_RESULTS_DIR
# - 无默认值（必须配置）
#
# 示例环境变量：
# SCAN_RESULTS_DIR=/data/scans

SCAN_RESULTS_DIR = os.getenv('SCAN_RESULTS_DIR')

# 扫描结果保留时间（单位：天）
# 
# 说明：
# - 由 cleanup_old_scans 定时任务使用（每天凌晨执行）
# - 基于目录修改时间（mtime）判断，不依赖数据库
# - 所有目录统一保留天数（不区分状态）
# 
# 配置方式：
# - 环境变量优先：SCAN_RETENTION_DAYS
# - 默认值：7 天
#
# 示例环境变量：
# SCAN_RETENTION_DAYS=14  # 所有扫描保留 14 天

SCAN_RESULTS_RETENTION_DAYS = int(os.getenv('SCAN_RETENTION_DAYS', '7'))


# ==================== 日志配置 ====================
# 日志配置说明：
# 1. 开发环境（DEBUG=True）：
#    - 默认 DEBUG 级别，输出详细调试信息
#    - 控制台彩色输出，便于调试
#    - 可选文件输出（配置 LOG_DIR）
#
# 2. 生产环境（DEBUG=False）：
#    - 默认 INFO 级别，只输出关键信息
#    - 同时输出到控制台和文件（配置 LOG_DIR）
#    - 文件自动轮转，避免日志文件过大
#
# 3. 环境变量控制：
#    - LOG_LEVEL: 全局日志级别（DEBUG/INFO/WARNING/ERROR/CRITICAL）
#    - LOG_DIR: 日志文件目录（留空则不输出文件）

from config.logging_config import get_logging_config

LOGGING = get_logging_config(debug=DEBUG)


