"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方应用
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    # 业务应用
    'apps.common',   # 通用工具
    'apps.targets',  # 扫描目标管理
    'apps.scan',     # 扫描任务管理
    'apps.engine',   # 扫描引擎管理
    'apps.asset',    # 资产管理
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS 中间件（必须在 CommonMiddleware 之前）
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # 已禁用 CSRF 校验
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 添加自定义模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database - PostgreSQL 配置
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'xingrin'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== REST Framework 配置 ====================
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'apps.common.pagination.BasePagination',  # 使用基础分页器
    
    # 禁用 CSRF 检查（所有环境）
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    
    # JSON 命名格式转换：后端 snake_case ↔ 前端 camelCase
    'DEFAULT_RENDERER_CLASSES': (
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',  # 响应数据转换为 camelCase
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',  # 浏览器 API 也使用 camelCase
    ),
    'DEFAULT_PARSER_CLASSES': (
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',  # 请求数据从 camelCase 转换为 snake_case
        'djangorestframework_camel_case.parser.CamelCaseFormParser',  # 表单数据也支持转换
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',  # 文件上传支持转换
    ),
    
    # 转换配置
    'JSON_UNDERSCOREIZE': {
        'no_underscore_before_number': True,  # 数字前不加下划线 (field1 不会变成 field_1)
    },
}

# ==================== CORS 配置 ====================
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

# ==================== CSRF 配置 ====================
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')

# ==================== Celery 配置 ====================
# Celery broker 配置（使用 Redis）
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Celery 结果后端（可选）
# CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
# CELERY_RESULT_EXPIRES = 3600  # 结果过期时间：1小时

# 任务序列化格式
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# 时区配置
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# 任务确认配置（确保任务不丢失）
CELERY_TASK_ACKS_LATE = True  # 任务执行完成后才确认
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # 每个 worker 只预取 1 个任务

# 超时配置
CELERY_TASK_TIME_LIMIT = 3600  # 硬超时：1小时（强制终止）
CELERY_TASK_SOFT_TIME_LIMIT = 3000  # 软超时：50分钟（抛出异常，允许清理）

# 队列路由配置（在 celery.py 中定义）
# 队列说明：
# - orchestrator: 编排任务（轻量级、高并发）
# - scans: 扫描任务（重量级、限制并发）


# ==================== 扫描结果存储和清理配置 ====================
# 扫描结果存储目录
# 
# 说明：
# - 所有扫描任务的工作空间都创建在此目录下
# - 清理任务会扫描此目录下的所有子目录
# - 必须配置，否则扫描任务无法创建工作空间
# 
# 配置方式：
# - 环境变量：SCAN_RESULTS_DIR
# - 无默认值（必须配置）
#
# 示例环境变量：
# SCAN_RESULTS_DIR=/data/scans

SCAN_RESULTS_DIR = os.getenv('SCAN_RESULTS_DIR')

# 扫描结果保留时间（单位：天）
# 
# 说明：
# - 由 cleanup_old_scans 定时任务使用（每天凌晨执行）
# - 基于目录修改时间（mtime）判断，不依赖数据库
# - 所有目录统一保留天数（不区分状态）
# 
# 配置方式：
# - 环境变量优先：SCAN_RETENTION_DAYS
# - 默认值：7 天
#
# 示例环境变量：
# SCAN_RETENTION_DAYS=14  # 所有扫描保留 14 天

SCAN_RESULTS_RETENTION_DAYS = int(os.getenv('SCAN_RETENTION_DAYS', '7'))

# ==================== 命令执行配置 ====================
# 命令执行超时时间（单位：秒）
# 
# 说明：
# - 用于控制扫描工具命令的最长执行时间
# - 防止命令无限期挂起导致资源耗尽
# - 适用于所有扫描工具（子域名发现、端口扫描、漏洞扫描等）
# 
# 配置方式：
# - 环境变量优先：COMMAND_TIMEOUT
# - 默认值：3600 秒（60分钟）
#
# 示例环境变量：
# COMMAND_TIMEOUT=7200  # 命令超时时间 2 小时

COMMAND_TIMEOUT = int(os.getenv('COMMAND_TIMEOUT', '3600'))

# 命令池最大并发数（单位：个）
# 
# 说明：
# - 控制系统级别同时执行的命令数量
# - 避免并发过高导致系统资源耗尽
# - 适用于所有使用 CommandPoolExecutor 的场景
# 
# 配置方式：
# - 环境变量优先：COMMAND_POOL_MAX_WORKERS
# - 默认值：5 个
#
# 示例环境变量：
# COMMAND_POOL_MAX_WORKERS=10  # 允许同时执行 10 个命令

COMMAND_POOL_MAX_WORKERS = int(os.getenv('COMMAND_POOL_MAX_WORKERS', '5'))

# 命令输出日志记录开关
# 
# 说明：
# - 控制是否将命令的详细输出（stdout/stderr）记录到日志文件
# - 开发环境下建议开启，便于调试和追踪命令执行情况
# - 生产环境可关闭以减少日志量
# 
# 配置方式：
# - 环境变量优先：COMMAND_LOG_OUTPUT
# - 默认值：False（不记录）
#
# 示例环境变量：
# COMMAND_LOG_OUTPUT=True  # 开启命令输出日志记录

COMMAND_LOG_OUTPUT = os.getenv('COMMAND_LOG_OUTPUT', 'False') == 'True'


# ==================== 日志配置 ====================
# 日志配置说明：
# 1. 开发环境（DEBUG=True）：
#    - 默认 DEBUG 级别，输出详细调试信息
#    - 控制台彩色输出，便于调试
#    - 可选文件输出（配置 LOG_DIR）
#
# 2. 生产环境（DEBUG=False）：
#    - 默认 INFO 级别，只输出关键信息
#    - 同时输出到控制台和文件（配置 LOG_DIR）
#    - 文件自动轮转，避免日志文件过大
#
# 3. 环境变量控制：
#    - LOG_LEVEL: 全局日志级别（DEBUG/INFO/WARNING/ERROR/CRITICAL）
#    - LOG_DIR: 日志文件目录（留空则不输出文件）
#    - SCAN_LOG_LEVEL: 扫描模块日志级别（可选，单独控制）
#    - CELERY_LOG_LEVEL: Celery 日志级别（可选，单独控制）

from config.logging_config import get_logging_config

LOGGING = get_logging_config(debug=DEBUG, base_dir=BASE_DIR)


