# Generated by Django 5.2.7 on 2025-11-12 14:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('engine', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, help_text='扫描实际开始时间（第一个任务开始执行时）', null=True)),
                ('stopped_at', models.DateTimeField(blank=True, help_text='扫描结束时间', null=True)),
                ('status', models.CharField(choices=[('cancelled', '已取消'), ('cancelling', '正在取消'), ('completed', '已完成'), ('crashed', '崩溃'), ('failed', '失败'), ('initiated', '初始化'), ('running', '运行中')], db_index=True, default='initiated', help_text='任务状态', max_length=20)),
                ('results_dir', models.CharField(blank=True, default='', help_text='结果存储目录', max_length=100)),
                ('flow_run_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Prefect Flow Run ID 列表（第一个为主 Flow Run ID）', size=None)),
                ('flow_run_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Flow Run 名称列表', size=None)),
                ('error_message', models.CharField(blank=True, default='', help_text='错误信息', max_length=2000)),
                ('dorks', models.ManyToManyField(blank=True, help_text='发现的 Google Dorks', related_name='scans', to='asset.dork')),
                ('emails', models.ManyToManyField(blank=True, help_text='发现的邮箱', related_name='scans', to='asset.email')),
                ('employees', models.ManyToManyField(blank=True, help_text='发现的员工信息', related_name='scans', to='asset.employee')),
                ('engine', models.ForeignKey(help_text='使用的扫描引擎', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='engine.scanengine')),
                ('s3_buckets', models.ManyToManyField(blank=True, help_text='发现的 S3 存储桶', related_name='scans', to='asset.s3bucket')),
                ('target', models.ForeignKey(help_text='扫描目标', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='targets.target')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'db_table': 'scan',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='scan_started_b9130f_idx'), models.Index(fields=['target'], name='scan_target__718b9d_idx')],
            },
        ),
    ]
