# Generated by Django 5.2.7 on 2025-11-02 06:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('engine', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='扫描开始时间')),
                ('stopped_at', models.DateTimeField(blank=True, help_text='扫描结束时间', null=True)),
                ('status', models.IntegerField(choices=[(-2, '中止'), (-1, '失败'), (0, '初始化'), (1, '运行中'), (2, '成功')], db_index=True, default=0, help_text='任务状态')),
                ('results_dir', models.CharField(blank=True, default='', help_text='结果存储目录', max_length=100)),
                ('task_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Celery 任务 ID 列表', size=None)),
                ('task_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), help_text='任务列表名称', null=True, size=None)),
                ('error_message', models.CharField(blank=True, default='', help_text='错误信息', max_length=300)),
                ('dorks', models.ManyToManyField(blank=True, help_text='发现的 Google Dorks', related_name='scans', to='asset.dork')),
                ('emails', models.ManyToManyField(blank=True, help_text='发现的邮箱', related_name='scans', to='asset.email')),
                ('employees', models.ManyToManyField(blank=True, help_text='发现的员工信息', related_name='scans', to='asset.employee')),
                ('engine', models.ForeignKey(help_text='使用的扫描引擎', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='engine.scanengine')),
                ('s3_buckets', models.ManyToManyField(blank=True, help_text='发现的 S3 存储桶', related_name='scans', to='asset.s3bucket')),
                ('target', models.ForeignKey(help_text='扫描目标', on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='targets.target')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
                'db_table': 'scan',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='任务名称', max_length=1000)),
                ('description', models.TextField(blank=True, default='', help_text='任务描述')),
                ('status', models.IntegerField(choices=[(-2, '中止'), (-1, '失败'), (0, '初始化'), (1, '运行中'), (2, '成功')], db_index=True, default=0, help_text='任务状态')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='任务更新时间')),
                ('error_message', models.CharField(blank=True, default='', help_text='任务失败时的错误信息（限制300字符）', max_length=300)),
                ('error_traceback', models.TextField(blank=True, default='', help_text='完整的错误堆栈信息（用于调试）')),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery 异步任务的唯一标识符', max_length=100)),
                ('scan', models.ForeignKey(blank=True, help_text='所属的扫描任务', null=True, on_delete=django.db.models.deletion.CASCADE, to='scan.scan')),
            ],
            options={
                'verbose_name': '扫描记录',
                'verbose_name_plural': '扫描记录',
                'db_table': 'scan_task',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['-started_at'], name='scan_started_b9130f_idx'),
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['-updated_at'], name='scan_task_updated_9cf117_idx'),
        ),
    ]
