# Generated by Django 5.2.7 on 2025-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='cached_vulns_critical',
            field=models.IntegerField(default=0, help_text='缓存的严重漏洞数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_vulns_high',
            field=models.IntegerField(default=0, help_text='缓存的高危漏洞数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_vulns_low',
            field=models.IntegerField(default=0, help_text='缓存的低危漏洞数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_vulns_medium',
            field=models.IntegerField(default=0, help_text='缓存的中危漏洞数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_vulns_total',
            field=models.IntegerField(default=0, help_text='缓存的漏洞总数'),
        ),
    ]
