# Generated by Django 5.2.7 on 2025-11-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], db_index=True, default='low', help_text='通知级别', max_length=20)),
                ('title', models.CharField(help_text='通知标题', max_length=200)),
                ('message', models.TextField(help_text='通知内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_read', models.BooleanField(default=False, help_text='是否已读')),
                ('read_at', models.DateTimeField(blank=True, help_text='阅读时间', null=True)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_c430f0_idx'), models.Index(fields=['level', '-created_at'], name='notificatio_level_0e5d12_idx'), models.Index(fields=['is_read', '-created_at'], name='notificatio_is_read_518ce0_idx')],
            },
        ),
    ]
