# Generated by Django 5.2.7 on 2025-11-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='扫描实际开始时间（第一个任务开始执行时）', null=True),
        ),
    ]
