# Generated by Django 5.2.7 on 2025-11-17 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
        ('scan', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ['-created_at'], 'verbose_name': '扫描任务', 'verbose_name_plural': '扫描任务'},
        ),
        migrations.RemoveIndex(
            model_name='scan',
            name='scan_started_b9130f_idx',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='started_at',
        ),
        migrations.AddField(
            model_name='scan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 17, 8, 16, 41, 791569, tzinfo=datetime.timezone.utc), help_text='任务创建时间'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['-created_at'], name='scan_created_0bb6c7_idx'),
        ),
    ]
