# Generated by Django 5.2.7 on 2025-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='current_stage',
            field=models.CharField(blank=True, default='', help_text='当前扫描阶段', max_length=50),
        ),
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0, help_text='扫描进度 0-100'),
        ),
        migrations.AddField(
            model_name='scan',
            name='stage_progress',
            field=models.JSONField(default=dict, help_text='各阶段进度详情'),
        ),
    ]
