# Generated by Django 5.2.7 on 2025-11-26 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
        ('scan', '0002_add_progress_tracking_fields'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='任务名称', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='任务描述')),
                ('frequency', models.CharField(choices=[('once', '仅一次'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('custom', '自定义 (Cron)')], default='daily', help_text='执行频率', max_length=20)),
                ('cron_expression', models.CharField(blank=True, default='', help_text='Cron 表达式（自定义频率时使用）', max_length=100)),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='是否启用')),
                ('deployment_id', models.CharField(blank=True, db_index=True, default='', help_text='Prefect Deployment ID', max_length=100)),
                ('run_count', models.IntegerField(default=0, help_text='已执行次数')),
                ('last_run_time', models.DateTimeField(blank=True, help_text='上次执行时间', null=True)),
                ('next_run_time', models.DateTimeField(blank=True, help_text='下次执行时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True)),
                ('engine', models.ForeignKey(help_text='使用的扫描引擎', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scans', to='engine.scanengine')),
                ('targets', models.ManyToManyField(help_text='扫描目标列表', related_name='scheduled_scans', to='targets.target')),
            ],
            options={
                'verbose_name': '定时扫描任务',
                'verbose_name_plural': '定时扫描任务',
                'db_table': 'scheduled_scan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scheduled_s_created_9b9c2e_idx'), models.Index(fields=['is_enabled', '-created_at'], name='scheduled_s_is_enab_23d660_idx'), models.Index(fields=['deleted_at', '-created_at'], name='scheduled_s_deleted_f9681e_idx')],
            },
        ),
    ]
