# Generated by Django 5.2.7 on 2025-11-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_alter_scan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='cached_directories_count',
            field=models.IntegerField(default=0, help_text='缓存的目录数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_endpoints_count',
            field=models.IntegerField(default=0, help_text='缓存的端点数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_ips_count',
            field=models.IntegerField(default=0, help_text='缓存的IP地址数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_subdomains_count',
            field=models.IntegerField(default=0, help_text='缓存的子域名数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='cached_websites_count',
            field=models.IntegerField(default=0, help_text='缓存的网站数量'),
        ),
        migrations.AddField(
            model_name='scan',
            name='stats_updated_at',
            field=models.DateTimeField(blank=True, help_text='统计数据最后更新时间', null=True),
        ),
    ]
