# Generated by Django 5.2.7 on 2025-11-13 02:33

from django.db import migrations, models


def forwards(apps, schema_editor):
    Notification = apps.get_model('scan', 'Notification')
    mapping = {
        'low': 'info',
        'medium': 'warning',
        'high': 'important',
    }
    for old, new in mapping.items():
        Notification.objects.filter(level=old).update(level=new)


def backwards(apps, schema_editor):
    Notification = apps.get_model('scan', 'Notification')
    mapping = {
        'info': 'low',
        'warning': 'medium',
        'important': 'high',
    }
    for old, new in mapping.items():
        Notification.objects.filter(level=old).update(level=new)


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_notification'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('important', '重要')], db_index=True, default='info', help_text='通知级别', max_length=20),
        ),
    ]
