# Generated by Django 5.2.7 on 2025-11-13 03:30

from django.db import migrations, models


def forwards(apps, schema_editor):
    Notification = apps.get_model('scan', 'Notification')
    mapping = {
        'info': 'low',
        'warning': 'medium',
        'important': 'high',
    }
    for old, new in mapping.items():
        Notification.objects.filter(level=old).update(level=new)


def backwards(apps, schema_editor):
    Notification = apps.get_model('scan', 'Notification')
    mapping = {
        'low': 'info',
        'medium': 'warning',
        'high': 'important',
    }
    for old, new in mapping.items():
        Notification.objects.filter(level=old).update(level=new)


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_alter_notification_level'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(
                choices=[('low', '低'), ('medium', '中'), ('high', '高')],
                db_index=True,
                default='low',
                help_text='通知级别',
                max_length=20,
            ),
        ),
    ]
