# Generated by Django 5.2.7 on 2025-11-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_add_scheduled_scan_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledscan',
            name='cron_expression',
        ),
        migrations.AddField(
            model_name='scheduledscan',
            name='run_day_of_month',
            field=models.IntegerField(default=1, help_text='每月几号执行（1-31，monthly 模式使用）'),
        ),
        migrations.AddField(
            model_name='scheduledscan',
            name='run_day_of_week',
            field=models.IntegerField(choices=[(0, '周日'), (1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六')], default=1, help_text='每周几执行（weekly 模式使用）'),
        ),
        migrations.AddField(
            model_name='scheduledscan',
            name='run_hour',
            field=models.IntegerField(default=2, help_text='执行小时（0-23）'),
        ),
        migrations.AddField(
            model_name='scheduledscan',
            name='run_minute',
            field=models.IntegerField(default=0, help_text='执行分钟（0-59）'),
        ),
        migrations.AlterField(
            model_name='scheduledscan',
            name='frequency',
            field=models.CharField(choices=[('once', '仅执行一次'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='daily', help_text='执行频率', max_length=20),
        ),
    ]
