# Generated by Django 5.2.7 on 2026-01-10 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_add_wecom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_mode',
            field=models.CharField(choices=[('full', '完整扫描'), ('quick', '快速扫描')], default='full', help_text='扫描模式：full=完整扫描，quick=快速扫描', max_length=10),
        ),
        migrations.CreateModel(
            name='ScanInputTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(help_text='用户输入的原始值', max_length=2000)),
                ('input_type', models.CharField(choices=[('domain', '域名'), ('ip', 'IP地址'), ('cidr', 'CIDR'), ('url', 'URL')], help_text='输入类型', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(help_text='所属的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='input_targets', to='scan.scan')),
            ],
            options={
                'verbose_name': '扫描输入目标',
                'verbose_name_plural': '扫描输入目标',
                'db_table': 'scan_input_target',
                'indexes': [models.Index(fields=['scan'], name='scan_input__scan_id_0a3227_idx'), models.Index(fields=['input_type'], name='scan_input__input_t_e3f681_idx')],
            },
        ),
    ]
