# Generated by Django 5.2.7 on 2025-11-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_fix_task_names_null'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scantask',
            new_name='scan_task_scan_id_edd895_idx',
            old_name='scan_task_scan_task_idx',
        ),
        migrations.RenameIndex(
            model_name='scantask',
            new_name='scan_task_scan_id_d5458d_idx',
            old_name='scan_task_scan_status_idx',
        ),
    ]
