# Generated by Django 5.2.7 on 2025-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_add_friendly_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledscan',
            name='interval_value',
            field=models.IntegerField(default=1, help_text='间隔值，如每5分钟、每2小时'),
        ),
        migrations.AddField(
            model_name='scheduledscan',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='一次性扫描的精确执行时间（once 模式使用）', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledscan',
            name='frequency',
            field=models.CharField(choices=[('once', '仅执行一次'), ('minutely', '每分钟'), ('hourly', '每小时'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='daily', help_text='执行频率', max_length=20),
        ),
    ]
