# Generated by Django 5.2.7 on 2025-11-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_add_interval_and_scheduled_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledscan',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='scheduledscan',
            name='interval_value',
        ),
        migrations.RemoveField(
            model_name='scheduledscan',
            name='run_day_of_month',
        ),
        migrations.RemoveField(
            model_name='scheduledscan',
            name='run_day_of_week',
        ),
        migrations.RemoveField(
            model_name='scheduledscan',
            name='run_hour',
        ),
        migrations.RemoveField(
            model_name='scheduledscan',
            name='run_minute',
        ),
        migrations.RemoveField(
            model_name='scheduledscan',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='scheduledscan',
            name='cron_expression',
            field=models.CharField(default='0 2 * * *', help_text='Cron 表达式，格式：分 时 日 月 周', max_length=100),
        ),
    ]
