# Generated by Django 5.2.7 on 2025-11-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_simplify_to_cron_expression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledscan',
            name='description',
        ),
    ]
