# Generated by Django 5.2.7 on 2025-11-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0010_increase_error_message_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('cancelled', '已取消'), ('cancelling', '正在取消'), ('completed', '已完成'), ('crashed', '崩溃'), ('failed', '失败'), ('initiated', '初始化'), ('running', '运行中')], db_index=True, default='initiated', help_text='任务状态', max_length=20),
        ),
    ]
