# Generated by Django 5.2.7 on 2025-11-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_port_subdomain_alter_endpoint_target_and_more'),
        ('engine', '0004_remove_command_model'),
        ('scan', '0011_alter_scan_status'),
        ('targets', '0003_remove_target_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['target'], name='scan_target__718b9d_idx'),
        ),
    ]
