# Generated by Django 5.2.7 on 2025-11-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='目标标识（域名/IP/CIDR）', max_length=300, unique=True)),
                ('target_type', models.CharField(choices=[('domain', '域名'), ('ip', 'IP地址'), ('cidr', 'CIDR范围')], db_index=True, default='domain', help_text='目标类型', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='目标描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('last_scanned_at', models.DateTimeField(blank=True, help_text='最后扫描时间', null=True)),
                ('request_headers', models.JSONField(blank=True, help_text='自定义请求头配置', null=True)),
            ],
            options={
                'verbose_name': '扫描目标',
                'verbose_name_plural': '扫描目标',
                'db_table': 'target',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type'], name='target_target__a3df87_idx'), models.Index(fields=['-created_at'], name='target_created_67f489_idx')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='组织名称', max_length=300, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='组织描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('targets', models.ManyToManyField(blank=True, help_text='所属目标列表', related_name='organizations', to='targets.target')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'organization',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='organizatio_created_012eac_idx')],
            },
        ),
    ]
