# Generated by Django 5.2.7 on 2025-11-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_organization_name_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='target',
            name='unique_target_name_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_organization_name_active'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name',), name='unique_target_name_active'),
        ),
    ]
