# Generated by Django 5.2.7 on 2025-11-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_is_dele_a8a863_idx',
        ),
        migrations.RemoveIndex(
            model_name='target',
            name='target_is_dele_46ad08_idx',
        ),
        migrations.RemoveIndex(
            model_name='target',
            name='target_is_dele_b1aa1e_idx',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='target',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='', help_text='组织名称', max_length=300),
        ),
        migrations.AlterField(
            model_name='target',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(blank=True, default='', help_text='目标标识（域名/IP/CIDR）', max_length=300),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['deleted_at', '-created_at'], name='organizatio_deleted_2c604f_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['deleted_at', '-created_at'], name='target_deleted_9fc9da_idx'),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['deleted_at', 'type'], name='target_deleted_306a89_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'deleted_at'), name='unique_organization_name_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='target',
            constraint=models.UniqueConstraint(fields=('name', 'deleted_at'), name='unique_target_name_not_deleted'),
        ),
    ]
