# Generated by Django 5.2.7 on 2025-11-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='target',
            name='target_target__a3df87_idx',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='target',
            name='request_headers',
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['type'], name='target_type_36a73c_idx'),
        ),
    ]
