# Generated by Django 5.2.7 on 2025-11-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_remove_target_target_target__a3df87_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='description',
        ),
    ]
