# Generated by Django 5.2.7 on 2025-11-29 12:01

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='最终访问的完整URL', max_length=2000)),
                ('host', models.CharField(blank=True, default='', help_text='主机名（域名或IP地址）', max_length=253)),
                ('location', models.CharField(blank=True, default='', help_text='重定向地址（HTTP 3xx 响应头 Location）', max_length=1000)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('title', models.CharField(blank=True, default='', help_text='网页标题（HTML <title> 标签内容）', max_length=1000)),
                ('webserver', models.CharField(blank=True, default='', help_text='服务器类型（HTTP 响应头 Server 值）', max_length=200)),
                ('body_preview', models.CharField(blank=True, default='', help_text='响应正文前N个字符（默认100个字符）', max_length=1000)),
                ('content_type', models.CharField(blank=True, default='', help_text='响应类型（HTTP Content-Type 响应头）', max_length=200)),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='技术栈（服务器/框架/语言等）', size=None)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('content_length', models.IntegerField(blank=True, help_text='响应体大小（单位字节）', null=True)),
                ('vhost', models.BooleanField(blank=True, help_text='是否支持虚拟主机', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('target', models.ForeignKey(help_text='所属的扫描目标（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='targets.target')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'db_table': 'website',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='完整请求 URL', max_length=2000)),
                ('status', models.IntegerField(blank=True, help_text='HTTP 响应状态码', null=True)),
                ('content_length', models.BigIntegerField(blank=True, help_text='响应体字节大小（Content-Length 或实际长度）', null=True)),
                ('words', models.IntegerField(blank=True, help_text='响应体中单词数量（按空格分割）', null=True)),
                ('lines', models.IntegerField(blank=True, help_text='响应体行数（按换行符分割）', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='响应头 Content-Type 值', max_length=200)),
                ('duration', models.BigIntegerField(blank=True, help_text='请求耗时（单位：纳秒）', null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('target', models.ForeignKey(blank=True, help_text='所属的扫描目标（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='targets.target')),
                ('website', models.ForeignKey(help_text='所属的站点（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='asset.website')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
                'db_table': 'directory',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='站点URL', max_length=2000)),
                ('host', models.CharField(blank=True, default='', help_text='主机名（域名或IP地址）', max_length=253)),
                ('title', models.CharField(blank=True, default='', help_text='页面标题', max_length=500)),
                ('status', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('content_length', models.BigIntegerField(blank=True, help_text='内容长度', null=True)),
                ('location', models.CharField(blank=True, default='', help_text='重定向位置', max_length=1000)),
                ('web_server', models.CharField(blank=True, default='', help_text='Web服务器', max_length=200)),
                ('content_type', models.CharField(blank=True, default='', help_text='内容类型', max_length=200)),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='技术栈', size=None)),
                ('body_preview', models.TextField(blank=True, default='', help_text='响应体预览')),
                ('vhost', models.BooleanField(blank=True, help_text='虚拟主机标志', null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('scan', models.ForeignKey(help_text='所属的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='website_snapshots', to='scan.scan')),
            ],
            options={
                'verbose_name': '网站快照',
                'verbose_name_plural': '网站快照',
                'db_table': 'website_snapshot',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorySnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='目录URL', max_length=2000)),
                ('status', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('content_length', models.BigIntegerField(blank=True, help_text='内容长度', null=True)),
                ('words', models.IntegerField(blank=True, help_text='响应体中单词数量（按空格分割）', null=True)),
                ('lines', models.IntegerField(blank=True, help_text='响应体行数（按换行符分割）', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='响应头 Content-Type 值', max_length=200)),
                ('duration', models.BigIntegerField(blank=True, help_text='请求耗时（单位：纳秒）', null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('scan', models.ForeignKey(help_text='所属的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='directory_snapshots', to='scan.scan')),
            ],
            options={
                'verbose_name': '目录快照',
                'verbose_name_plural': '目录快照',
                'db_table': 'directory_snapshot',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['scan'], name='directory_s_scan_id_c45900_idx'), models.Index(fields=['url'], name='directory_s_url_b4b72b_idx'), models.Index(fields=['-discovered_at'], name='directory_s_discove_edb413_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'url'), name='unique_directory_per_scan_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='最终访问的完整URL', max_length=2000)),
                ('host', models.CharField(blank=True, default='', help_text='主机名（域名或IP地址）', max_length=253)),
                ('location', models.CharField(blank=True, default='', help_text='重定向地址（HTTP 3xx 响应头 Location）', max_length=1000)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('title', models.CharField(blank=True, default='', help_text='网页标题（HTML <title> 标签内容）', max_length=1000)),
                ('webserver', models.CharField(blank=True, default='', help_text='服务器类型（HTTP 响应头 Server 值）', max_length=200)),
                ('body_preview', models.CharField(blank=True, default='', help_text='响应正文前N个字符（默认100个字符）', max_length=1000)),
                ('content_type', models.CharField(blank=True, default='', help_text='响应类型（HTTP Content-Type 响应头）', max_length=200)),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='技术栈（服务器/框架/语言等）', size=None)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('content_length', models.IntegerField(blank=True, help_text='响应体大小（单位字节）', null=True)),
                ('vhost', models.BooleanField(blank=True, help_text='是否支持虚拟主机', null=True)),
                ('matched_gf_patterns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='匹配的GF模式列表，用于识别敏感端点（如api, debug, config等）', size=None)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('target', models.ForeignKey(help_text='所属的扫描目标（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='targets.target')),
            ],
            options={
                'verbose_name': '端点',
                'verbose_name_plural': '端点',
                'db_table': 'endpoint',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['-discovered_at'], name='endpoint_discove_09f023_idx'), models.Index(fields=['target'], name='endpoint_target__7f9065_idx'), models.Index(fields=['url'], name='endpoint_url_30f66e_idx'), models.Index(fields=['host'], name='endpoint_host_5b4cc8_idx'), models.Index(fields=['deleted_at', '-discovered_at'], name='endpoint_deleted_c37deb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('url', 'target'), name='unique_endpoint_url_target_active')],
            },
        ),
        migrations.CreateModel(
            name='EndpointSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='端点URL', max_length=2000)),
                ('host', models.CharField(blank=True, default='', help_text='主机名（域名或IP地址）', max_length=253)),
                ('title', models.CharField(blank=True, default='', help_text='页面标题', max_length=1000)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('content_length', models.IntegerField(blank=True, help_text='内容长度', null=True)),
                ('location', models.CharField(blank=True, default='', help_text='重定向位置', max_length=1000)),
                ('webserver', models.CharField(blank=True, default='', help_text='Web服务器', max_length=200)),
                ('content_type', models.CharField(blank=True, default='', help_text='内容类型', max_length=200)),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='技术栈', size=None)),
                ('body_preview', models.CharField(blank=True, default='', help_text='响应体预览', max_length=1000)),
                ('vhost', models.BooleanField(blank=True, help_text='虚拟主机标志', null=True)),
                ('matched_gf_patterns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='匹配的GF模式列表', size=None)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('scan', models.ForeignKey(help_text='所属的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_snapshots', to='scan.scan')),
            ],
            options={
                'verbose_name': '端点快照',
                'verbose_name_plural': '端点快照',
                'db_table': 'endpoint_snapshot',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['scan'], name='endpoint_sn_scan_id_6ac9a7_idx'), models.Index(fields=['url'], name='endpoint_sn_url_205160_idx'), models.Index(fields=['host'], name='endpoint_sn_host_577bfd_idx'), models.Index(fields=['-discovered_at'], name='endpoint_sn_discove_b16f7b_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'url'), name='unique_endpoint_per_scan_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='HostPortMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(help_text='主机名（域名或IP）', max_length=1000)),
                ('ip', models.GenericIPAddressField(help_text='IP地址')),
                ('port', models.IntegerField(help_text='端口号（1-65535）', validators=[django.core.validators.MinValueValidator(1, message='端口号必须大于等于1'), django.core.validators.MaxValueValidator(65535, message='端口号必须小于等于65535')])),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('target', models.ForeignKey(help_text='所属的扫描目标', on_delete=django.db.models.deletion.CASCADE, related_name='host_port_mappings', to='targets.target')),
            ],
            options={
                'verbose_name': '主机端口映射',
                'verbose_name_plural': '主机端口映射',
                'db_table': 'host_port_mapping',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['target'], name='host_port_m_target__943e9b_idx'), models.Index(fields=['host'], name='host_port_m_host_f78363_idx'), models.Index(fields=['ip'], name='host_port_m_ip_2e6f02_idx'), models.Index(fields=['port'], name='host_port_m_port_9fb9ff_idx'), models.Index(fields=['host', 'ip'], name='host_port_m_host_3ce245_idx'), models.Index(fields=['-discovered_at'], name='host_port_m_discove_1ba4ee_idx'), models.Index(fields=['deleted_at', '-discovered_at'], name='host_port_m_deleted_dd6451_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('target', 'host', 'ip', 'port'), name='unique_target_host_ip_port_active')],
            },
        ),
        migrations.CreateModel(
            name='HostPortMappingSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(help_text='主机名（域名或IP）', max_length=1000)),
                ('ip', models.GenericIPAddressField(help_text='IP地址')),
                ('port', models.IntegerField(help_text='端口号（1-65535）', validators=[django.core.validators.MinValueValidator(1, message='端口号必须大于等于1'), django.core.validators.MaxValueValidator(65535, message='端口号必须小于等于65535')])),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('scan', models.ForeignKey(help_text='所属的扫描任务（主关联）', on_delete=django.db.models.deletion.CASCADE, related_name='host_port_mapping_snapshots', to='scan.scan')),
            ],
            options={
                'verbose_name': '主机端口映射快照',
                'verbose_name_plural': '主机端口映射快照',
                'db_table': 'host_port_mapping_snapshot',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['scan'], name='host_port_m_scan_id_50ba0b_idx'), models.Index(fields=['host'], name='host_port_m_host_e99054_idx'), models.Index(fields=['ip'], name='host_port_m_ip_54818c_idx'), models.Index(fields=['port'], name='host_port_m_port_ed7b48_idx'), models.Index(fields=['host', 'ip'], name='host_port_m_host_8a463a_idx'), models.Index(fields=['scan', 'host'], name='host_port_m_scan_id_426fdb_idx'), models.Index(fields=['-discovered_at'], name='host_port_m_discove_a2098b_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'host', 'ip', 'port'), name='unique_scan_host_ip_port_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='子域名名称', max_length=1000)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='首次发现时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('target', models.ForeignKey(help_text='所属的扫描目标（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='targets.target')),
            ],
            options={
                'verbose_name': '子域名',
                'verbose_name_plural': '子域名',
                'db_table': 'subdomain',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['-discovered_at'], name='subdomain_discove_3351c9_idx'), models.Index(fields=['name', 'target'], name='subdomain_name_60e1d0_idx'), models.Index(fields=['target'], name='subdomain_target__e409f0_idx'), models.Index(fields=['name'], name='subdomain_name_d40ba7_idx'), models.Index(fields=['deleted_at', '-discovered_at'], name='subdomain_deleted_d9eb0a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'target'), name='unique_name_target_active')],
            },
        ),
        migrations.CreateModel(
            name='SubdomainSnapshot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='子域名名称', max_length=1000)),
                ('discovered_at', models.DateTimeField(auto_now_add=True, help_text='发现时间')),
                ('scan', models.ForeignKey(help_text='所属的扫描任务', on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_snapshots', to='scan.scan')),
            ],
            options={
                'verbose_name': '子域名快照',
                'verbose_name_plural': '子域名快照',
                'db_table': 'subdomain_snapshot',
                'ordering': ['-discovered_at'],
                'indexes': [models.Index(fields=['scan'], name='subdomain_s_scan_id_68c253_idx'), models.Index(fields=['name'], name='subdomain_s_name_2da42b_idx'), models.Index(fields=['-discovered_at'], name='subdomain_s_discove_671036_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'name'), name='unique_subdomain_per_scan_snapshot')],
            },
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['-discovered_at'], name='website_discove_25d55f_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['url'], name='website_url_b18883_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['host'], name='website_host_996b50_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['target'], name='website_target__2a353b_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['deleted_at', '-discovered_at'], name='website_deleted_ae2bf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('url', 'target'), name='unique_website_url_target_active'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['-discovered_at'], name='directory_discove_a51a79_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['target'], name='directory_target__e310c8_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['deleted_at', '-discovered_at'], name='directory_deleted_eada1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('website', 'url'), name='unique_directory_url_website_active'),
        ),
        migrations.AddIndex(
            model_name='websitesnapshot',
            index=models.Index(fields=['scan'], name='website_sna_scan_id_26b6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesnapshot',
            index=models.Index(fields=['url'], name='website_sna_url_801a70_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesnapshot',
            index=models.Index(fields=['host'], name='website_sna_host_348fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesnapshot',
            index=models.Index(fields=['-discovered_at'], name='website_sna_discove_468ccb_idx'),
        ),
        migrations.AddConstraint(
            model_name='websitesnapshot',
            constraint=models.UniqueConstraint(fields=('scan', 'url'), name='unique_website_per_scan_snapshot'),
        ),
    ]
