# Generated by Django 5.2.7 on 2025-11-12 14:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='', help_text='Dork 类型', max_length=500)),
                ('url', models.CharField(blank=True, default='', help_text='URL 地址', max_length=10000)),
            ],
            options={
                'verbose_name': 'Google Dork',
                'verbose_name_plural': 'Google Dorks',
                'db_table': 'dork',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, default='', help_text='邮箱地址', max_length=200)),
                ('password', models.CharField(blank=True, default='', help_text='邮箱密码', max_length=200)),
            ],
            options={
                'verbose_name': '邮箱',
                'verbose_name_plural': '邮箱',
                'db_table': 'email',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='员工姓名', max_length=1000)),
                ('designation', models.CharField(blank=True, default='', help_text='职位', max_length=1000)),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(help_text='完整的HTTP URL（如 http://api.example.com/v1/users）')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('content_length', models.IntegerField(blank=True, help_text='HTTP响应体大小（字节），由httpx或ffuf探测获取', null=True)),
                ('page_title', models.TextField(blank=True, default='', help_text='网页标题（HTML title标签内容），由httpx探测获取')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP响应状态码（如200, 404, 500等），由httpx或ffuf探测获取', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='HTTP响应的Content-Type（如text/html, application/json等），由httpx探测获取', max_length=100)),
                ('response_time', models.FloatField(blank=True, help_text='HTTP响应时间（秒），用于性能分析，由httpx探测获取', null=True)),
                ('webserver', models.CharField(blank=True, default='', help_text='Web服务器信息（如nginx/1.19.0, Apache/2.4.41等），从Server响应头获取', max_length=1000)),
                ('is_default', models.BooleanField(default=False, help_text='是否为子域名的默认根端点（如 http://api.example.com/）')),
                ('matched_gf_patterns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='匹配的GF模式列表，用于识别敏感端点（如api, debug, config等）', size=None)),
            ],
            options={
                'verbose_name': '端点',
                'verbose_name_plural': '端点',
                'db_table': 'endpoint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, default='', help_text='IP地址', max_length=500)),
                ('protocol_version', models.CharField(blank=True, default='', help_text='协议版本（如IPv4, IPv6）', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_private', models.BooleanField(default=False, help_text='是否私有IP')),
                ('reverse_pointer', models.CharField(blank=True, default='', help_text='反向解析（如域名）', max_length=500)),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
                'db_table': 'ip_address',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, help_text='端口号', null=True)),
                ('description', models.CharField(blank=True, default='', help_text='端口描述（如http, https, ssh, ftp等）', max_length=500)),
                ('service_name', models.CharField(blank=True, default='', help_text='服务名称（如http, https, ssh, ftp等）', max_length=500)),
                ('is_uncommon', models.BooleanField(default=False, help_text='是否为不常见端口')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '端口',
                'verbose_name_plural': '端口',
                'db_table': 'port',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='S3Bucket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='存储桶名称', max_length=500)),
                ('region', models.CharField(blank=True, default='', help_text='区域', max_length=500)),
                ('provider', models.CharField(blank=True, default='', help_text='云服务提供商', max_length=100)),
                ('owner_id', models.CharField(blank=True, default='', help_text='所有者 ID', max_length=250)),
                ('owner_display_name', models.CharField(blank=True, default='', help_text='所有者显示名称', max_length=250)),
                ('perm_auth_users_read', models.IntegerField(default=0, help_text='认证用户读权限')),
                ('perm_auth_users_write', models.IntegerField(default=0, help_text='认证用户写权限')),
                ('perm_auth_users_read_acl', models.IntegerField(default=0, help_text='认证用户读 ACL 权限')),
                ('perm_auth_users_write_acl', models.IntegerField(default=0, help_text='认证用户写 ACL 权限')),
                ('perm_auth_users_full_control', models.IntegerField(default=0, help_text='认证用户完全控制权限')),
                ('perm_all_users_read', models.IntegerField(default=0, help_text='所有用户读权限')),
                ('perm_all_users_write', models.IntegerField(default=0, help_text='所有用户写权限')),
                ('perm_all_users_read_acl', models.IntegerField(default=0, help_text='所有用户读 ACL 权限')),
                ('perm_all_users_write_acl', models.IntegerField(default=0, help_text='所有用户写 ACL 权限')),
                ('perm_all_users_full_control', models.IntegerField(default=0, help_text='所有用户完全控制权限')),
                ('num_objects', models.IntegerField(default=0, help_text='对象数量')),
                ('size', models.IntegerField(default=0, help_text='存储桶大小（字节）')),
            ],
            options={
                'verbose_name': 'S3 存储桶',
                'verbose_name_plural': 'S3 存储桶',
                'db_table': 's3_bucket',
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='子域名名称', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间，也就是首次发现时间')),
                ('cname', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='CNAME记录列表，由httpx探测获取', size=None)),
                ('is_cdn', models.BooleanField(default=False, help_text='是否使用CDN（由httpx的cdn探测标志判断）')),
                ('cdn_name', models.CharField(blank=True, default='', help_text='CDN提供商名称（如cloudflare, akamai等）', max_length=200)),
            ],
            options={
                'verbose_name': '子域名',
                'verbose_name_plural': '子域名',
                'db_table': 'subdomain',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', help_text='技术名称', max_length=500)),
            ],
            options={
                'verbose_name': '站点技术',
                'verbose_name_plural': '站点技术',
                'db_table': 'technology',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='站点url', max_length=1000)),
                ('screenshot_path', models.CharField(blank=True, default='', help_text='截图路径', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('title', models.CharField(blank=True, default='', help_text='页面标题', max_length=1000)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('content_length', models.IntegerField(blank=True, help_text='内容长度（字节）', null=True)),
                ('response_time', models.IntegerField(blank=True, help_text='响应时间（毫秒）', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='HTTP响应的Content-Type（如text/html, application/json等）', max_length=200)),
                ('webserver', models.CharField(blank=True, default='', help_text='Web服务器（如nginx, apache等）', max_length=200)),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'db_table': 'website',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ffuf_command', models.CharField(blank=True, default='', help_text='ffuf命令', max_length=500)),
                ('start_scan_at', models.DateTimeField(blank=True, help_text='开始扫描时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '目录扫描',
                'verbose_name_plural': '目录扫描',
                'db_table': 'directory_scan',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='directory_s_created_b380f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredPath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.IntegerField(blank=True, help_text='长度', null=True)),
                ('lines', models.IntegerField(blank=True, help_text='行数', null=True)),
                ('words', models.IntegerField(blank=True, help_text='单词数', null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('name', models.CharField(blank=True, default='', help_text='路径名称', max_length=500)),
                ('url', models.CharField(blank=True, default='', help_text='URL地址', max_length=5000)),
                ('content_type', models.CharField(blank=True, default='', help_text='内容类型', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('directory_scan', models.ForeignKey(blank=True, help_text='所属的目录扫描', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovered_paths', to='asset.directoryscan')),
            ],
            options={
                'verbose_name': '目录扫描结果',
                'verbose_name_plural': '目录扫描结果',
                'db_table': 'discovered_path',
                'ordering': ['-created_at'],
            },
        ),
    ]
