# Generated by Django 5.2.7 on 2025-11-19 01:16

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(help_text='IP地址', max_length=500)),
                ('protocol_version', models.CharField(blank=True, default='', help_text='协议版本（如IPv4, IPv6）', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('is_private', models.BooleanField(default=False, help_text='是否私有IP')),
                ('reverse_pointer', models.CharField(blank=True, default='', help_text='反向解析（如域名）', max_length=500)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('scan', models.ForeignKey(blank=True, help_text='所属的扫描任务（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='scan.scan')),
                ('target', models.ForeignKey(blank=True, help_text='所属的扫描目标（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='targets.target')),
            ],
            options={
                'verbose_name': 'IP地址',
                'verbose_name_plural': 'IP地址',
                'db_table': 'ip_address',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='子域名名称', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间，也就是首次发现时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('cname', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='CNAME记录列表，由httpx探测获取', size=None)),
                ('is_cdn', models.BooleanField(default=False, help_text='是否使用CDN（由httpx的cdn探测标志判断）')),
                ('cdn_name', models.CharField(blank=True, default='', help_text='CDN提供商名称（如cloudflare, akamai等）', max_length=200)),
                ('scan', models.ForeignKey(blank=True, help_text='所属的扫描任务（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='scan.scan')),
                ('target', models.ForeignKey(help_text='所属的扫描目标（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='targets.target')),
            ],
            options={
                'verbose_name': '子域名',
                'verbose_name_plural': '子域名',
                'db_table': 'subdomain',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='端口号（1-65535）', validators=[django.core.validators.MinValueValidator(1, message='端口号必须大于等于1'), django.core.validators.MaxValueValidator(65535, message='端口号必须小于等于65535')])),
                ('description', models.CharField(blank=True, default='', help_text='端口描述（如http, https, ssh, ftp等）', max_length=500)),
                ('service_name', models.CharField(blank=True, default='', help_text='服务名称（如http, https, ssh, ftp等）', max_length=500)),
                ('is_uncommon', models.BooleanField(default=False, help_text='是否为不常见端口')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('ip_address', models.ForeignKey(help_text='所属的IP地址（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='asset.ipaddress')),
                ('subdomain', models.ForeignKey(blank=True, help_text='所属的子域名（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='asset.subdomain')),
            ],
            options={
                'verbose_name': '端口',
                'verbose_name_plural': '端口',
                'db_table': 'port',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='subdomain',
            field=models.ForeignKey(help_text='所属的子域名（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='asset.subdomain'),
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='最终访问的完整URL', max_length=2000)),
                ('location', models.CharField(blank=True, default='', help_text='重定向地址（HTTP 3xx 响应头 Location）', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='扫描或探测时间')),
                ('title', models.CharField(blank=True, default='', help_text='网页标题（HTML <title> 标签内容）', max_length=1000)),
                ('webserver', models.CharField(blank=True, default='', help_text='服务器类型（HTTP 响应头 Server 值）', max_length=200)),
                ('body_preview', models.CharField(blank=True, default='', help_text='响应正文前N个字符（默认100个字符）', max_length=1000)),
                ('content_type', models.CharField(blank=True, default='', help_text='响应类型（HTTP Content-Type 响应头）', max_length=200)),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='技术栈（服务器/框架/语言等）', size=None)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP状态码', null=True)),
                ('content_length', models.IntegerField(blank=True, help_text='响应体大小（单位字节）', null=True)),
                ('vhost', models.BooleanField(blank=True, help_text='是否支持虚拟主机', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('scan', models.ForeignKey(blank=True, help_text='所属的扫描任务（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='scan.scan')),
                ('subdomain', models.ForeignKey(help_text='所属的子域名（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='asset.subdomain')),
                ('target', models.ForeignKey(blank=True, help_text='所属的扫描目标（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='targets.target')),
            ],
            options={
                'verbose_name': '站点',
                'verbose_name_plural': '站点',
                'db_table': 'website',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='完整的HTTP URL（如 http://api.example.com/v1/users）', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('content_length', models.IntegerField(blank=True, help_text='HTTP响应体大小（字节），由httpx或ffuf探测获取', null=True)),
                ('page_title', models.CharField(blank=True, default='', help_text='网页标题（HTML title标签内容），由httpx探测获取', max_length=1000)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP响应状态码（如200, 404, 500等），由httpx或ffuf探测获取', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='HTTP响应的Content-Type（如text/html, application/json等），由httpx探测获取', max_length=100)),
                ('response_time', models.FloatField(blank=True, help_text='HTTP响应时间（秒），用于性能分析，由httpx探测获取', null=True)),
                ('webserver', models.CharField(blank=True, default='', help_text='Web服务器信息（如nginx/1.19.0, Apache/2.4.41等），从Server响应头获取', max_length=1000)),
                ('is_default', models.BooleanField(default=False, help_text='是否为子域名的默认根端点（如 http://api.example.com/）')),
                ('matched_gf_patterns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='匹配的GF模式列表，用于识别敏感端点（如api, debug, config等）', size=None)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('scan', models.ForeignKey(blank=True, help_text='所属的扫描任务（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scan.scan')),
                ('target', models.ForeignKey(help_text='所属的扫描目标（冗余字段，用于快速查询）', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='targets.target')),
                ('website', models.ForeignKey(help_text='所属的站点（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='asset.website')),
            ],
            options={
                'verbose_name': '端点',
                'verbose_name_plural': '端点',
                'db_table': 'endpoint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='完整请求 URL', max_length=2000)),
                ('status', models.IntegerField(blank=True, help_text='HTTP 响应状态码', null=True)),
                ('length', models.BigIntegerField(blank=True, help_text='响应体字节大小（Content-Length 或实际长度）', null=True)),
                ('words', models.IntegerField(blank=True, help_text='响应体中单词数量（按空格分割）', null=True)),
                ('lines', models.IntegerField(blank=True, help_text='响应体行数（按换行符分割）', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='响应头 Content-Type 值', max_length=200)),
                ('duration', models.BigIntegerField(blank=True, help_text='请求耗时（单位：纳秒）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='删除时间（NULL表示未删除）', null=True)),
                ('scan', models.ForeignKey(blank=True, help_text='所属的扫描任务（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='scan.scan')),
                ('target', models.ForeignKey(blank=True, help_text='所属的扫描目标（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='targets.target')),
                ('website', models.ForeignKey(help_text='所属的站点（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='asset.website')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
                'db_table': 'directory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['-created_at'], name='subdomain_created_e187a8_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['name', 'target'], name='subdomain_name_60e1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['target'], name='subdomain_target__e409f0_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['scan'], name='subdomain_scan_id_263e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['name'], name='subdomain_name_d40ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['deleted_at', '-created_at'], name='subdomain_deleted_cffdab_idx'),
        ),
        migrations.AddConstraint(
            model_name='subdomain',
            constraint=models.UniqueConstraint(fields=('name', 'target', 'deleted_at'), name='unique_name_target_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['-created_at'], name='port_created_e5c841_idx'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['deleted_at', '-created_at'], name='port_deleted_5b6935_idx'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('ip_address', 'number', 'deleted_at'), name='unique_port_ip_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['-created_at'], name='ip_address_created_d3f565_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['target'], name='ip_address_target__66a31d_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['scan'], name='ip_address_scan_id_f8b04c_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['deleted_at', '-created_at'], name='ip_address_deleted_0e4401_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(fields=('subdomain', 'ip', 'deleted_at'), name='unique_ip_subdomain_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['-created_at'], name='website_created_c9cfd2_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['url'], name='website_url_b18883_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['target'], name='website_target__2a353b_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['scan'], name='website_scan_id_9167bc_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['deleted_at', '-created_at'], name='website_deleted_f780bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('url', 'subdomain', 'deleted_at'), name='unique_url_subdomain_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['-created_at'], name='endpoint_created_44fe9c_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['scan'], name='endpoint_scan_id_2cd3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['target'], name='endpoint_target__7f9065_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['deleted_at', '-created_at'], name='endpoint_deleted_49aeaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('url', 'website', 'deleted_at'), name='unique_url_website_not_deleted'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['-created_at'], name='directory_created_2cef03_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['scan'], name='directory_scan_id_4c4637_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['target'], name='directory_target__e310c8_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['deleted_at', '-created_at'], name='directory_deleted_2ca253_idx'),
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(fields=('website', 'url', 'deleted_at'), name='unique_directory_url_website_not_deleted'),
        ),
    ]
