# Generated by Django 5.2.7 on 2025-11-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('scan', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='endpoint',
            name='unique_url_website_active',
        ),
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_url_target_active',
        ),
        migrations.RemoveIndex(
            model_name='endpoint',
            name='endpoint_website_922ee2_idx',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='website',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='host',
            field=models.CharField(blank=True, default='', help_text='主机名（域名或IP地址）', max_length=253),
        ),
        migrations.AddField(
            model_name='endpointsnapshot',
            name='host',
            field=models.CharField(blank=True, default='', help_text='主机名（域名或IP地址）', max_length=253),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='target',
            field=models.ForeignKey(help_text='所属的扫描目标（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='targets.target'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['host'], name='endpoint_host_5b4cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointsnapshot',
            index=models.Index(fields=['host'], name='endpoint_sn_host_577bfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('url', 'target'), name='unique_endpoint_url_target_active'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('url', 'target'), name='unique_website_url_target_active'),
        ),
    ]
