# Generated by Django 5.2.7 on 2025-11-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('scan', '0001_initial'),
        ('targets', '0002_remove_organization_unique_organization_name_not_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='directory',
            name='unique_directory_url_website_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='endpoint',
            name='unique_url_website_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='ipaddress',
            name='unique_ip_subdomain_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='port',
            name='unique_port_ip_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='subdomain',
            name='unique_name_target_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='website',
            name='unique_url_subdomain_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='directory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('website', 'url'), name='unique_directory_url_website_active'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('url', 'website'), name='unique_url_website_active'),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('subdomain', 'ip'), name='unique_ip_subdomain_active'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('ip_address', 'number'), name='unique_port_ip_active'),
        ),
        migrations.AddConstraint(
            model_name='subdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'target'), name='unique_name_target_active'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('url', 'subdomain'), name='unique_url_subdomain_active'),
        ),
    ]
