# Generated by Django 5.2.7 on 2025-11-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorysnapshot',
            name='content_type',
            field=models.CharField(blank=True, default='', help_text='响应头 Content-Type 值', max_length=200),
        ),
        migrations.AddField(
            model_name='directorysnapshot',
            name='duration',
            field=models.BigIntegerField(blank=True, help_text='请求耗时（单位：纳秒）', null=True),
        ),
        migrations.AddField(
            model_name='directorysnapshot',
            name='lines',
            field=models.IntegerField(blank=True, help_text='响应体行数（按换行符分割）', null=True),
        ),
        migrations.AddField(
            model_name='directorysnapshot',
            name='words',
            field=models.IntegerField(blank=True, help_text='响应体中单词数量（按空格分割）', null=True),
        ),
    ]
