# Generated by Django 5.2.7 on 2025-11-15 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('scan', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='完整请求 URL', max_length=2000)),
                ('status', models.IntegerField(blank=True, help_text='HTTP 响应状态码', null=True)),
                ('length', models.BigIntegerField(blank=True, help_text='响应体字节大小（Content-Length 或实际长度）', null=True)),
                ('words', models.IntegerField(blank=True, help_text='响应体中单词数量（按空格分割）', null=True)),
                ('lines', models.IntegerField(blank=True, help_text='响应体行数（按换行符分割）', null=True)),
                ('content_type', models.CharField(blank=True, default='', help_text='响应头 Content-Type 值', max_length=200)),
                ('duration', models.BigIntegerField(blank=True, help_text='请求耗时（单位：纳秒）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('scan', models.ForeignKey(blank=True, help_text='所属的扫描任务（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='scan.scan')),
                ('target', models.ForeignKey(blank=True, help_text='所属的扫描目标（冗余字段，用于快速查询）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='targets.target')),
                ('website', models.ForeignKey(help_text='所属的站点（主关联字段，表示所属关系，不能为空）', on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='asset.website')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
                'db_table': 'directory',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='directory_created_2cef03_idx')],
                'constraints': [models.UniqueConstraint(fields=('website', 'url'), name='unique_directory_url_website')],
            },
        ),
    ]
