# Generated by Django 5.2.7 on 2025-11-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('scan', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveredpath',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='所属的扫描任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovered_paths', to='scan.scan'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='所属的扫描任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='scan.scan'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='target',
            field=models.ForeignKey(help_text='所属的扫描目标', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='targets.target'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='所属的扫描任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='scan.scan'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='target',
            field=models.ForeignKey(blank=True, help_text='所属的扫描目标', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='targets.target'),
        ),
        migrations.AddField(
            model_name='port',
            name='ip',
            field=models.ForeignKey(blank=True, help_text='所属的IP地址', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='asset.ipaddress'),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='所属的扫描任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='scan.scan'),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='target',
            field=models.ForeignKey(help_text='所属的扫描目标', on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='targets.target'),
        ),
        migrations.AddField(
            model_name='port',
            name='subdomain',
            field=models.ForeignKey(blank=True, help_text='所属的子域名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='asset.subdomain'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='subdomain',
            field=models.ForeignKey(blank=True, help_text='所属的子域名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='asset.subdomain'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='subdomain',
            field=models.ForeignKey(blank=True, help_text='所属的子域名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='asset.subdomain'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='technology',
            field=models.ManyToManyField(blank=True, help_text='所属的站点技术', related_name='endpoints', to='asset.technology'),
        ),
        migrations.AddField(
            model_name='website',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='所属的扫描任务', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='scan.scan'),
        ),
        migrations.AddField(
            model_name='website',
            name='subdomain',
            field=models.ForeignKey(blank=True, help_text='所属的子域名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='asset.subdomain'),
        ),
        migrations.AddField(
            model_name='website',
            name='target',
            field=models.ForeignKey(blank=True, help_text='所属的扫描目标', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='targets.target'),
        ),
        migrations.AddField(
            model_name='website',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='所属的站点技术', related_name='websites', to='asset.technology'),
        ),
        migrations.AddField(
            model_name='discoveredpath',
            name='website',
            field=models.ForeignKey(blank=True, help_text='所属的站点', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovered_paths', to='asset.website'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['-created_at'], name='subdomain_created_e187a8_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['name', 'target_id'], name='subdomain_name_60e1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['target_id'], name='subdomain_target__e409f0_idx'),
        ),
        migrations.AddIndex(
            model_name='subdomain',
            index=models.Index(fields=['scan_id'], name='subdomain_scan_id_263e3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='subdomain',
            constraint=models.UniqueConstraint(fields=('name', 'target_id'), name='unique_subdomain_per_scan'),
        ),
        migrations.AddIndex(
            model_name='port',
            index=models.Index(fields=['-created_at'], name='port_created_e5c841_idx'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('ip', 'number'), name='unique_port_per_ip'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['-created_at'], name='ip_address_created_d3f565_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(fields=('subdomain', 'ip'), name='unique_ip_per_subdomain'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['-created_at'], name='endpoint_created_44fe9c_idx'),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['-created_at'], name='website_created_c9cfd2_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredpath',
            index=models.Index(fields=['-created_at'], name='discovered__created_16002a_idx'),
        ),
    ]
