# Generated by Django 5.2.7 on 2025-11-13 09:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
        ('scan', '0004_alter_notification_level'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='website',
            name='screenshot_path',
        ),
        migrations.RemoveField(
            model_name='website',
            name='technologies',
        ),
        migrations.AddField(
            model_name='website',
            name='body_preview',
            field=models.TextField(blank=True, default='', help_text='响应正文前N个字符（默认100个字符）'),
        ),
        migrations.AddField(
            model_name='website',
            name='location',
            field=models.CharField(blank=True, default='', help_text='重定向地址（HTTP 3xx 响应头 Location）', max_length=1000),
        ),
        migrations.AddField(
            model_name='website',
            name='tech',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='技术栈（服务器/框架/语言等）', size=None),
        ),
        migrations.AddField(
            model_name='website',
            name='vhost',
            field=models.BooleanField(blank=True, help_text='是否支持虚拟主机', null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='content_length',
            field=models.IntegerField(blank=True, help_text='响应体大小（单位字节）', null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='content_type',
            field=models.CharField(blank=True, default='', help_text='响应类型（HTTP Content-Type 响应头）', max_length=200),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(blank=True, help_text='扫描或探测时间', null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(blank=True, default='', help_text='网页标题（HTML <title> 标签内容）', max_length=1000),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(help_text='最终访问的完整URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='website',
            name='webserver',
            field=models.CharField(blank=True, default='', help_text='服务器类型（HTTP 响应头 Server 值）', max_length=200),
        ),
        migrations.AddIndex(
            model_name='website',
            index=models.Index(fields=['url'], name='website_url_b18883_idx'),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(fields=('url',), name='unique_website_url'),
        ),
    ]
