# Generated by Django 5.2.7 on 2025-11-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_directorysnapshot_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorysnapshot',
            name='location',
        ),
    ]
