# Generated by Django 5.2.7 on 2025-11-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_directory'),
        ('scan', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['scan'], name='directory_scan_id_4c4637_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['target'], name='directory_target__e310c8_idx'),
        ),
    ]
