# Generated by Django 5.2.7 on 2025-12-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_vulnerability_raw_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_targets', models.IntegerField(default=0, help_text='目标总数')),
                ('total_subdomains', models.IntegerField(default=0, help_text='子域名总数')),
                ('total_ips', models.IntegerField(default=0, help_text='IP地址总数')),
                ('total_endpoints', models.IntegerField(default=0, help_text='端点总数')),
                ('total_websites', models.IntegerField(default=0, help_text='网站总数')),
                ('total_vulns', models.IntegerField(default=0, help_text='漏洞总数')),
                ('total_assets', models.IntegerField(default=0, help_text='总资产数（子域名+IP+端点+网站）')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
            ],
            options={
                'verbose_name': '资产统计',
                'verbose_name_plural': '资产统计',
                'db_table': 'asset_statistics',
            },
        ),
    ]
