# Generated by Django 5.2.7 on 2025-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_assetstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetstatistics',
            name='prev_assets',
            field=models.IntegerField(default=0, help_text='上次总资产数'),
        ),
        migrations.AddField(
            model_name='assetstatistics',
            name='prev_endpoints',
            field=models.IntegerField(default=0, help_text='上次端点总数'),
        ),
        migrations.AddField(
            model_name='assetstatistics',
            name='prev_ips',
            field=models.IntegerField(default=0, help_text='上次IP地址总数'),
        ),
        migrations.AddField(
            model_name='assetstatistics',
            name='prev_subdomains',
            field=models.IntegerField(default=0, help_text='上次子域名总数'),
        ),
        migrations.AddField(
            model_name='assetstatistics',
            name='prev_targets',
            field=models.IntegerField(default=0, help_text='上次目标总数'),
        ),
        migrations.AddField(
            model_name='assetstatistics',
            name='prev_vulns',
            field=models.IntegerField(default=0, help_text='上次漏洞总数'),
        ),
        migrations.AddField(
            model_name='assetstatistics',
            name='prev_websites',
            field=models.IntegerField(default=0, help_text='上次网站总数'),
        ),
    ]
