# Generated by Django 5.2.7 on 2025-11-11 01:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_change_subdomain_unique_constraint'),
        ('scan', '0011_alter_scan_status'),
        ('targets', '0003_remove_target_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subdomain',
            name='unique_subdomain_per_scan',
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='matched_gf_patterns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='匹配的GF模式列表，用于识别敏感端点（如api, debug, config等）', size=None),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='page_title',
            field=models.TextField(blank=True, default='', help_text='网页标题（HTML title标签内容），由httpx探测获取'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='url',
            field=models.TextField(help_text='完整的HTTP URL（如 http://api.example.com/v1/users）'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='cname',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='CNAME记录列表，由httpx探测获取', size=None),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间，也就是首次发现时间'),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='target',
            field=models.ForeignKey(help_text='所属的扫描目标', on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='targets.target'),
        ),
        migrations.AddConstraint(
            model_name='subdomain',
            constraint=models.UniqueConstraint(fields=('name', 'target_id'), name='unique_subdomain_per_scan'),
        ),
    ]
