# Generated by Django 5.2.7 on 2025-11-12 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_remove_subdomain_unique_subdomain_per_scan_and_more'),
        ('scan', '0011_alter_scan_status'),
        ('targets', '0003_remove_target_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='subdomain',
            field=models.ForeignKey(blank=True, help_text='所属的子域名', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='asset.subdomain'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='target',
            field=models.ForeignKey(help_text='所属的扫描目标', on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='targets.target'),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(fields=('subdomain', 'ip'), name='unique_ip_per_subdomain'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('ip', 'number'), name='unique_port_per_ip'),
        ),
    ]
