# Generated by Django 5.2.7 on 2025-11-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_add_subdomain_name_target_composite_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subdomain',
            new_name='subdomain_name_60e1d0_idx',
            old_name='subdomain_name_target_idx',
        ),
    ]
