# Generated by Django 5.2.7 on 2025-11-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEngine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='引擎名称', max_length=200, unique=True)),
                ('configuration', models.TextField(blank=True, default='', help_text='引擎配置，yaml 格式')),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认引擎')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '扫描引擎',
                'verbose_name_plural': '扫描引擎',
                'db_table': 'scan_engine',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scan_engine_created_da4870_idx'), models.Index(fields=['is_default'], name='scan_engine_is_defa_6b1132_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_scan_engine')],
            },
        ),
    ]
