# Generated by Django 5.2.7 on 2025-11-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='节点名称', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='VPS 公网 IP')),
                ('ssh_port', models.IntegerField(default=22, help_text='SSH 端口')),
                ('username', models.CharField(default='root', help_text='SSH 用户名', max_length=50)),
                ('password', models.CharField(blank=True, default='', help_text='SSH 密码', max_length=200)),
                ('last_seen', models.DateTimeField(blank=True, help_text='最后心跳时间', null=True)),
                ('info', models.JSONField(blank=True, default=dict, help_text='系统信息(CPU/内存/磁盘)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worker 节点',
                'db_table': 'worker_node',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEngine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='引擎名称', max_length=200, unique=True)),
                ('configuration', models.CharField(blank=True, default='', help_text='引擎配置，yaml 格式', max_length=10000)),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认引擎')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '扫描引擎',
                'verbose_name_plural': '扫描引擎',
                'db_table': 'scan_engine',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scan_engine_created_da4870_idx'), models.Index(fields=['is_default'], name='scan_engine_is_defa_6b1132_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_scan_engine')],
            },
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='字典名称，唯一', max_length=200, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='字典描述', max_length=200)),
                ('file_path', models.CharField(help_text='后端保存的字典文件绝对路径', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小（字节）')),
                ('line_count', models.IntegerField(default=0, help_text='字典行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '字典文件',
                'verbose_name_plural': '字典文件',
                'db_table': 'wordlist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='wordlist_created_4afb02_idx')],
            },
        ),
    ]
