# Generated by Django 5.2.7 on 2025-11-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('command_line', models.TextField(help_text='执行的命令行，如: subfinder -d example.com -o output.txt')),
                ('exit_code', models.IntegerField(blank=True, help_text='命令退出码', null=True)),
                ('output', models.TextField(blank=True, default='', help_text='命令的标准输出内容')),
                ('started_at', models.DateTimeField(help_text='命令执行开始时间')),
            ],
            options={
                'verbose_name': '命令',
                'verbose_name_plural': '命令',
                'db_table': 'command',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEngine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='引擎名称', max_length=200, unique=True)),
                ('configuration', models.TextField(blank=True, default='', help_text='引擎配置，yaml 格式')),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认引擎')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
            options={
                'verbose_name': '扫描引擎',
                'verbose_name_plural': '扫描引擎',
                'db_table': 'scan_engine',
                'ordering': ['-created_at'],
            },
        ),
    ]
