# Generated by Django 5.2.7 on 2025-11-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='节点名称', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='VPS 公网 IP')),
                ('ssh_port', models.IntegerField(default=22, help_text='SSH 端口')),
                ('username', models.CharField(default='root', help_text='SSH 用户名', max_length=50)),
                ('status', models.CharField(choices=[('pending', '等待部署'), ('installing', '正在安装'), ('online', '运行中'), ('offline', '离线'), ('error', '错误')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worker 节点',
                'db_table': 'worker_node',
                'ordering': ['-created_at'],
            },
        ),
    ]
