# Generated by Django 5.2.7 on 2025-11-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='字典名称，唯一', max_length=200, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='字典描述', max_length=200)),
                ('file_path', models.CharField(help_text='后端保存的字典文件绝对路径', max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小（字节）')),
                ('line_count', models.IntegerField(default=0, help_text='字典行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '字典文件',
                'verbose_name_plural': '字典文件',
                'db_table': 'wordlist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='wordlist_created_4afb02_idx')],
            },
        ),
    ]
