# Generated by Django 5.2.7 on 2025-12-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleiGitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.CharField(blank=True, default='', help_text='Nuclei 模板 Git 仓库地址', max_length=500)),
                ('auth_type', models.CharField(default='none', help_text='认证方式：none / token', max_length=20)),
                ('auth_token', models.TextField(blank=True, default='', help_text='访问凭据（Token 或私钥内容）')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
            ],
            options={
                'verbose_name': 'Nuclei Git 仓库配置',
                'verbose_name_plural': 'Nuclei Git 仓库配置',
                'db_table': 'nuclei_git_settings',
            },
        ),
    ]
