# Generated by Django 5.2.7 on 2025-11-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='scan',
            field=models.ForeignKey(blank=True, help_text='所属的扫描任务', null=True, on_delete=django.db.models.deletion.CASCADE, to='scan.scan'),
        ),
        migrations.AddField(
            model_name='command',
            name='task',
            field=models.ForeignKey(blank=True, help_text='所属的扫描记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='scan.scantask'),
        ),
        migrations.AddIndex(
            model_name='scanengine',
            index=models.Index(fields=['-created_at'], name='scan_engine_created_da4870_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['-started_at'], name='command_started_4059a5_idx'),
        ),
    ]
