# Generated by Django 5.2.7 on 2025-11-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_workernode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workernode',
            name='password',
            field=models.CharField(blank=True, default='', help_text='SSH 密码', max_length=200),
        ),
    ]
