# Generated by Django 5.2.7 on 2025-12-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_nucleigitsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleiTemplateRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='仓库名称，用于前端展示', max_length=200)),
                ('repo_url', models.CharField(help_text='Git 仓库地址', max_length=500)),
                ('auth_type', models.CharField(default='none', help_text='认证方式：none / token', max_length=20)),
                ('auth_token', models.TextField(blank=True, default='', help_text='访问凭据（Token 或私钥内容）')),
                ('local_path', models.CharField(help_text='本地工作目录绝对路径', max_length=500)),
                ('branch', models.CharField(blank=True, default='', help_text='Git 分支名，可选', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认模板仓库')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='最后一次成功同步时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': 'Nuclei 模板仓库',
                'verbose_name_plural': 'Nuclei 模板仓库',
                'db_table': 'nuclei_template_repo',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_nuclei_template_repo')],
            },
        ),
    ]
