# Generated by Django 5.2.7 on 2025-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scanengine',
            index=models.Index(fields=['is_default'], name='scan_engine_is_defa_6b1132_idx'),
        ),
        migrations.AddConstraint(
            model_name='scanengine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_scan_engine'),
        ),
    ]
