# Generated by Django 5.2.7 on 2025-11-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_scanengine_scan_engine_is_defa_6b1132_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
