# Generated by Django 5.2.7 on 2025-11-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_workernode_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='workernode',
            name='info',
            field=models.JSONField(blank=True, default=dict, help_text='系统信息(CPU/内存/磁盘)'),
        ),
        migrations.AddField(
            model_name='workernode',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='最后心跳时间', null=True),
        ),
    ]
