# Generated by Django 5.2.7 on 2025-12-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_nucleitemplaterepo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NucleiGitSettings',
        ),
        migrations.RemoveConstraint(
            model_name='nucleitemplaterepo',
            name='unique_default_nuclei_template_repo',
        ),
        migrations.RemoveField(
            model_name='nucleitemplaterepo',
            name='is_default',
        ),
    ]
