# Generated by Django 5.2.7 on 2025-12-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_delete_nucleigitsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nucleitemplaterepo',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='nucleitemplaterepo',
            name='auth_type',
        ),
        migrations.RemoveField(
            model_name='nucleitemplaterepo',
            name='branch',
        ),
    ]
