# Generated by Django 5.2.7 on 2025-11-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_workernode_info_workernode_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workernode',
            name='status',
        ),
    ]
