# Generated by Django 5.2.7 on 2025-12-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_remove_nucleitemplaterepo_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='file_hash',
            field=models.CharField(blank=True, default='', help_text='文件 SHA-256 哈希，用于缓存校验', max_length=64),
        ),
    ]
