# Generated by Django 5.2.7 on 2025-12-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_wordlist_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='nucleitemplaterepo',
            name='commit_hash',
            field=models.CharField(blank=True, default='', help_text='最后同步的 Git commit hash，用于 Worker 版本校验', max_length=40),
        ),
        migrations.AlterField(
            model_name='nucleitemplaterepo',
            name='local_path',
            field=models.CharField(blank=True, default='', help_text='本地工作目录绝对路径', max_length=500),
        ),
        migrations.AlterField(
            model_name='nucleitemplaterepo',
            name='name',
            field=models.CharField(help_text='仓库名称，用于前端展示和配置引用', max_length=200, unique=True),
        ),
    ]
