# Generated by Django 5.2.7 on 2025-12-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_nucleitemplaterepo_commit_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanengine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新时间'),
        ),
    ]
