// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/domains/create": {
            "post": {
                "description": "批量创建域名并自动关联到指定组织（支持单个或多个域名）。如果域名已存在，会复用现有域名并建立关联关系",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名管理"
                ],
                "summary": "批量创建域名",
                "parameters": [
                    {
                        "description": "域名创建请求，包含域名列表和组织ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.CreateDomainsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功，返回创建的域名列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误（如域名列表为空、参数格式错误等）",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/domains/remove-from-organization": {
            "post": {
                "description": "解除指定组织与域名的关联关系，如果域名成为孤儿（没有任何组织关联）则自动删除该域名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名管理"
                ],
                "summary": "解除组织与域名的关联（待实现完善）",
                "parameters": [
                    {
                        "description": "解除关联请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.RemoveOrgDomainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "解除关联成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.RemoveOrgDomainResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "组织、域名或关联不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/domains/update": {
            "post": {
                "description": "更新域名信息（名称和描述）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名管理"
                ],
                "summary": "更新域名",
                "parameters": [
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.UpdateDomainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "域名不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/domains/{id}": {
            "get": {
                "description": "根据域名ID获取域名的详细信息（不包含子域名）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名管理"
                ],
                "summary": "获取单个域名详情",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "域名ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "域名不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除域名，会级联删除所有关联的子域名、端点和漏洞数据",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名管理"
                ],
                "summary": "删除域名",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "域名ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.DeleteDomainResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "域名不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/domains/{id}/subdomains": {
            "get": {
                "description": "根据域名ID获取该域名下的所有子域名（支持分页和排序）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名管理"
                ],
                "summary": "获取域名的子域名列表",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "域名ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量,默认10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段: id, name, created_at, updated_at,默认updated_at",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序方向: asc, desc,默认desc",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.GetSubDomainsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "域名不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations": {
            "get": {
                "description": "获取所有组织列表，支持分页和排序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "获取组织列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "example": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "id",
                            "name",
                            "created_at",
                            "updated_at"
                        ],
                        "type": "string",
                        "default": "updated_at",
                        "description": "排序字段",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.GetOrgsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "请求参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations/batch-delete": {
            "post": {
                "description": "批量删除组织（级联删除关联的域名和孤儿域名）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "批量删除组织（待实现完善）",
                "parameters": [
                    {
                        "description": "组织ID列表",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.BatchDeleteOrgsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "批量删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.BatchDeleteOrgsResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "业务逻辑错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "422": {
                        "description": "请求参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations/create": {
            "post": {
                "description": "创建新的组织",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "创建组织",
                "parameters": [
                    {
                        "description": "组织信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.CreateOrgRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Organization"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "422": {
                        "description": "请求参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations/delete": {
            "post": {
                "description": "删除指定的组织（级联删除关联的域名和孤儿域名）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "删除组织（待实现完善）",
                "parameters": [
                    {
                        "description": "删除请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.DeleteOrgRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.DeleteOrgResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "组织不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "422": {
                        "description": "请求参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations/update": {
            "post": {
                "description": "更新组织信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "更新组织",
                "parameters": [
                    {
                        "description": "更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.UpdateOrgRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Organization"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "组织不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "422": {
                        "description": "请求参数验证失败",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations/{id}": {
            "get": {
                "description": "根据组织ID获取组织的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "获取单个组织详情",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "组织ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Organization"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "组织不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations/{id}/domains": {
            "get": {
                "description": "获取指定组织的所有域名，支持分页和排序。注意：返回的域名不包含子域名信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域名管理"
                ],
                "summary": "获取组织的域名列表",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "组织ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "created_at",
                            "updated_at"
                        ],
                        "type": "string",
                        "default": "updated_at",
                        "description": "排序字段",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.GetOrgDomainsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/organizations/{id}/subdomains": {
            "get": {
                "description": "根据组织ID获取该组织所有域名下的子域名（支持分页和排序）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "组织管理"
                ],
                "summary": "获取组织的子域名列表",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "组织ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量,默认10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段: id, name, created_at, updated_at,默认updated_at",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序方向: asc, desc,默认desc",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.GetSubDomainsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "组织不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/subdomains": {
            "get": {
                "description": "获取所有子域名，支持分页和排序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "子域名管理"
                ],
                "summary": "获取所有子域名列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码,默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量,默认10",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序字段: id, name, created_at, updated_at,默认updated_at",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "排序方向: asc, desc,默认desc",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取子域名列表成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.GetSubDomainsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/subdomains/create": {
            "post": {
                "description": "批量创建子域名并关联到指定域名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "子域名管理"
                ],
                "summary": "批量创建子域名",
                "parameters": [
                    {
                        "description": "子域名创建请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.CreateSubDomainsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.CreateSubDomainsResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        },
        "/subdomains/{id}": {
            "get": {
                "description": "根据子域名ID获取子域名的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "子域名管理"
                ],
                "summary": "获取单个子域名详情",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "子域名ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/vulun-scan-backend_internal_models.SubDomain"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "404": {
                        "description": "子域名不存在",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "vulun-scan-backend_internal_models.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP状态码，如 \"200\", \"400\", \"500\"",
                    "type": "string"
                },
                "data": {
                    "description": "响应数据"
                },
                "message": {
                    "description": "响应消息",
                    "type": "string"
                },
                "state": {
                    "description": "业务状态，如 \"success\", \"error\"",
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.BatchDeleteOrgsRequest": {
            "type": "object",
            "required": [
                "organization_ids"
            ],
            "properties": {
                "organization_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "vulun-scan-backend_internal_models.BatchDeleteOrgsResponseData": {
            "type": "object",
            "properties": {
                "deleted_count": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "organizations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Organization"
                    }
                }
            }
        },
        "vulun-scan-backend_internal_models.CreateDomainsRequest": {
            "type": "object",
            "required": [
                "domains",
                "organization_id"
            ],
            "properties": {
                "domains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.DomainDetail"
                    }
                },
                "organization_id": {
                    "type": "integer"
                }
            }
        },
        "vulun-scan-backend_internal_models.CreateOrgRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.CreateSubDomainsRequest": {
            "type": "object",
            "required": [
                "domain_id",
                "sub_domains"
            ],
            "properties": {
                "domain_id": {
                    "type": "integer"
                },
                "sub_domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "vulun-scan-backend_internal_models.CreateSubDomainsResponseData": {
            "type": "object",
            "properties": {
                "existing_domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success_count": {
                    "type": "integer"
                },
                "total_requested": {
                    "type": "integer"
                }
            }
        },
        "vulun-scan-backend_internal_models.DeleteDomainResponseData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.DeleteOrgRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "vulun-scan-backend_internal_models.DeleteOrgResponseData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.Domain": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "endpoints": {
                    "description": "Endpoint 的级联删除：删除 Domain 时自动删除其所有端点",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Endpoint"
                    }
                },
                "id": {
                    "description": "数据库基础字段",
                    "type": "integer"
                },
                "name": {
                    "description": "核心业务字段",
                    "type": "string"
                },
                "organizations": {
                    "description": "关联关系 - 级联删除配置在 OrganizationDomain 中间表定义",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Organization"
                    }
                },
                "sub_domains": {
                    "description": "SubDomain 的级联删除：删除 Domain 时自动删除其所有子域名",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.SubDomain"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "vulnerabilities": {
                    "description": "Vulnerability 的级联删除：删除 Domain 时自动删除其所有漏洞",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Vulnerability"
                    }
                }
            }
        },
        "vulun-scan-backend_internal_models.DomainDetail": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.Endpoint": {
            "type": "object",
            "properties": {
                "content_length": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "domain": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                        }
                    ]
                },
                "domain_id": {
                    "type": "integer"
                },
                "id": {
                    "description": "数据库基础字段",
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "subdomain": {
                    "$ref": "#/definitions/vulun-scan-backend_internal_models.SubDomain"
                },
                "subdomain_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "description": "核心业务字段",
                    "type": "string"
                },
                "vulnerabilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Vulnerability"
                    }
                }
            }
        },
        "vulun-scan-backend_internal_models.GetOrgDomainsResponse": {
            "type": "object",
            "properties": {
                "domains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "vulun-scan-backend_internal_models.GetOrgsResponse": {
            "type": "object",
            "properties": {
                "organizations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Organization"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "vulun-scan-backend_internal_models.GetSubDomainsResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "sub_domains": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.SubDomain"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "vulun-scan-backend_internal_models.Organization": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "domains": {
                    "description": "关联关系 - 级联删除配置在 OrganizationDomain 中间表定义",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                    }
                },
                "id": {
                    "description": "数据库基础字段",
                    "type": "integer"
                },
                "name": {
                    "description": "核心业务字段",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.RemoveOrgDomainRequest": {
            "type": "object",
            "required": [
                "domain_id",
                "organization_id"
            ],
            "properties": {
                "domain_id": {
                    "type": "integer"
                },
                "organization_id": {
                    "type": "integer"
                }
            }
        },
        "vulun-scan-backend_internal_models.RemoveOrgDomainResponseData": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.SubDomain": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "domain": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                        }
                    ]
                },
                "domain_id": {
                    "type": "integer"
                },
                "endpoints": {
                    "description": "Endpoint 的级联删除：删除 SubDomain 时自动删除其所有端点",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Endpoint"
                    }
                },
                "id": {
                    "description": "数据库基础字段",
                    "type": "integer"
                },
                "name": {
                    "description": "核心业务字段",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "vulnerabilities": {
                    "description": "Vulnerability 的级联删除：删除 SubDomain 时自动删除其所有漏洞",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vulun-scan-backend_internal_models.Vulnerability"
                    }
                }
            }
        },
        "vulun-scan-backend_internal_models.UpdateDomainRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.UpdateOrgRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "vulun-scan-backend_internal_models.Vulnerability": {
            "type": "object",
            "properties": {
                "affected_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "curl_command": {
                    "type": "string"
                },
                "cve": {
                    "type": "string"
                },
                "cvss": {
                    "type": "number"
                },
                "cvss_metrics": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "discovered_date": {
                    "description": "发现和状态信息",
                    "type": "string"
                },
                "domain_id": {
                    "type": "integer"
                },
                "domain_name": {
                    "description": "优化字段 - 冗余域名名称减少联表查询",
                    "type": "string"
                },
                "domain_relation": {
                    "description": "关联关系",
                    "allOf": [
                        {
                            "$ref": "#/definitions/vulun-scan-backend_internal_models.Domain"
                        }
                    ]
                },
                "endpoint_id": {
                    "type": "integer"
                },
                "endpoint_relation": {
                    "$ref": "#/definitions/vulun-scan-backend_internal_models.Endpoint"
                },
                "extracted_results": {
                    "description": "扫描结果",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hackerone_report_id": {
                    "description": "外部集成",
                    "type": "string"
                },
                "http_url": {
                    "type": "string"
                },
                "id": {
                    "description": "数据库基础字段",
                    "type": "integer"
                },
                "impact": {
                    "type": "string"
                },
                "is_gpt_used": {
                    "type": "boolean"
                },
                "open_status": {
                    "type": "boolean"
                },
                "organization": {
                    "description": "组织信息",
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                },
                "poc": {
                    "description": "技术细节",
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "remediation": {
                    "type": "string"
                },
                "request": {
                    "type": "string"
                },
                "response": {
                    "type": "string"
                },
                "risk_score": {
                    "type": "integer"
                },
                "scan_history_id": {
                    "description": "扫描历史",
                    "type": "integer"
                },
                "service": {
                    "type": "string"
                },
                "severity": {
                    "description": "-1:unknown, 0:info, 1:low, 2:medium, 3:high, 4:critical",
                    "type": "integer"
                },
                "solution": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subdomain_id": {
                    "description": "关联关系 - 灵活归属",
                    "type": "integer"
                },
                "subdomain_relation": {
                    "$ref": "#/definitions/vulun-scan-backend_internal_models.SubDomain"
                },
                "target_domain": {
                    "type": "string"
                },
                "title": {
                    "description": "核心漏洞信息",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Vulun Scan Backend API",
	Description:      "漏洞扫描系统后端 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
